#!/usr/bin/env python3
"""Validate designer-authored tutorial XLSX, then atomically publish runtime JSON.

Reuses the canonical player importer's dependency-free OOXML reader. No runtime
Excel dependency, formulas, expressions, command strings or geometry fields.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
import tempfile
from pathlib import Path

# Keep authoring runs from leaving generated bytecode beside committed scripts.
sys.dont_write_bytecode = True
from ImportCanonicalPlayerContent import read_sheet_rows, ValidationFailure

SCHEMA_VERSION = 1
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ContentSource/Tutorial/FMCodex_Guided_Match.xlsx"
OUTPUT = ROOT / "Content/Data/CanonicalGuidedMatchContent.json"
HEADERS = {
    "Lessons": "LessonId SchemaVersion Enabled TitleCN ComparisonTitleCN Notes".split(),
    "Steps": "LessonId StepId SurfaceType TitleCN BodyCN SecondaryCN CTA_CN FocusTargetId ArrowPlacement ShowExit PointerCN Notes".split(),
    "Emphasis": "LessonId StepId Field MatchText Occurrence Style".split(),
    "Timings": "LessonId TimingId Value Notes".split(),
    "Labels": "LessonId LabelId TextCN Notes".split(),
}
SURFACES = {"ExplanationPanel", "CompactActionBar"}
TARGETS = {"None", "Button.TacticalPoint", "PlayerHand.Carrier", "Deployment.Carrier", "Button.EndDeployment",
           "Field.Carrier", "Button.LongShot", "Theater.DirectShot", "Formula.AttackBaseValue", "Button.AttackRoll",
           "FullCard.Skill.LongShot", "FullCard.Attribute.SHO", "FullCard.Trait.LongShotCarrier",
           "Opponent.Deployment", "Header.Opponent", "Field.Marker"}
ARROWS = {"Auto", "Above", "Side", "None"}
VARIABLES = {"Carrier.DisplayName", "Carrier.Shooting", "FirstCarrier.DisplayName", "FirstCarrier.Shooting",
             "ComparisonCarrier.DisplayName", "ComparisonCarrier.Shooting", "Marker.DisplayName",
             "CurrentAttackTP", "LongShot.SkillMin", "LongShot.SkillMax", "LongShot.TraitName", "Formula.AttackBaseValue"}
STEPS = "Intro TacticPoint TacticPointExplanation InspectGyokeres InspectOdegaard ShootingExplanation SkillRangeExplanation TraitExplanation Deploy Deploy.Comparison Deploy.Hint1 Deploy.Hint2 OpponentDeploy OpponentDeploy.After FinishExplanation FinishDeployment OpponentFinish OpponentFinish.After CarrierExplanation Carrier OpponentMarker OpponentMarker.After SkillExplanation Skill DirectExplanation DirectShot FormulaHover FormulaExplanation AttackRoll OpponentDefense ResultReveal FailurePause Rewind Rewind.Unexpected RewindTransition Summary Summary.Unexpected Complete".split()
ACK_STEPS = set("Intro TacticPointExplanation ShootingExplanation SkillRangeExplanation TraitExplanation FinishExplanation CarrierExplanation SkillExplanation DirectExplanation FormulaExplanation Rewind Rewind.Unexpected Summary Summary.Unexpected Complete".split())
TIMINGS = "OpponentPreAction OpponentDeployAttention OpponentDeployMove OpponentDeploySettledHold OpponentChoiceFocus OpponentFinishFocus OpponentDestinationHold OpponentSettledHold OpponentDefenseLead FailureFollowupDelay ComparisonPace RewindDelay HintFirstDelay HintSecondDelay FeedbackDuration".split()
LABELS = "ExitTitle ExitBody ExitCancel ExitConfirm OpponentPointer LocalRack OpponentRack UnavailableChoice DeploymentTarget FeedbackCompare FeedbackUnavailable ProgressFirst ProgressComparison".split()
IDENTIFIER = re.compile(r"^[A-Za-z][A-Za-z0-9.]*$")
TOKEN = re.compile(r"\{([A-Za-z][A-Za-z0-9.]*)\}")


def require(ok, message):
    if not ok:
        raise ValidationFailure(message)


def placeholders(text):
    require(isinstance(text, str), "copy must be text")
    keys = TOKEN.findall(text)
    require(not (set(keys) - VARIABLES), f"Unknown placeholder in {text!r}")
    remaining = TOKEN.sub("", text)
    require(not any(c in remaining for c in "{}<>&"), f"Malformed placeholder/rich-text markup in {text!r}")
    return keys


def emphasis_range(text, match, occurrence):
    start = -len(match)
    for _ in range(occurrence):
        start = text.find(match, start + len(match))
        require(start >= 0, f"Emphasis {match!r} occurrence {occurrence} not found in {text!r}")
    end = start + len(match)
    for token in TOKEN.finditer(text):
        require(not (start < token.end() and end > token.start()) or
                (start <= token.start() and end >= token.end()), "Emphasis cuts a placeholder")
    return start, end


def validate(data):
    require(data.get("schemaVersion") == SCHEMA_VERSION, "Unsupported tutorial schemaVersion")
    lessons = {}
    for lesson in data["lessons"]:
        lid = lesson["LessonId"]
        require(bool(IDENTIFIER.fullmatch(lid)) and lid not in lessons, f"Duplicate/invalid LessonId: {lid}")
        require(lesson["SchemaVersion"] == SCHEMA_VERSION, f"{lid}: unsupported schema")
        require(type(lesson["Enabled"]) is bool, f"{lid}: Enabled must be boolean")
        require(bool(lesson["TitleCN"]) and bool(lesson["ComparisonTitleCN"]), f"{lid}: titles required")
        require(not placeholders(lesson["TitleCN"]) and not placeholders(lesson["ComparisonTitleCN"]), "Lesson titles do not support dynamic bindings")
        lessons[lid] = lesson
    indexes = {}
    for group, key in (("steps", "StepId"), ("timings", "TimingId"), ("labels", "LabelId")):
        index = {}
        for row in data[group]:
            identity = row["LessonId"], row[key]
            require(identity[0] in lessons, f"Unknown LessonId: {identity[0]}")
            require(bool(IDENTIFIER.fullmatch(identity[1])) and identity not in index, f"Duplicate/invalid {key}: {identity}")
            index[identity] = row
        indexes[group] = index
    for row in data["steps"]:
        sid = row["StepId"]
        require(row["SurfaceType"] in SURFACES, f"{sid}: invalid SurfaceType")
        require(row["FocusTargetId"] in TARGETS, f"{sid}: invalid FocusTargetId")
        require(row["ArrowPlacement"] in ARROWS, f"{sid}: invalid ArrowPlacement")
        require(type(row["ShowExit"]) is bool, f"{sid}: ShowExit must be boolean")
        require(bool(row["TitleCN"]) and (bool(row["BodyCN"]) or sid == "FailurePause"), f"{sid}: title/body required")
        for field in ("TitleCN", "BodyCN", "SecondaryCN", "CTA_CN", "PointerCN"):
            keys = placeholders(row[field])
            if row["LessonId"] == "Lesson01":
                require("CurrentAttackTP" not in keys or sid not in {"Intro", "TacticPoint"}, f"{sid}: CurrentAttackTP not yet available")
                require("Formula.AttackBaseValue" not in keys or sid in {"FormulaHover", "FormulaExplanation", "AttackRoll", "OpponentDefense", "ResultReveal", "FailurePause", "Rewind", "Rewind.Unexpected", "Summary", "Summary.Unexpected", "Complete"}, f"{sid}: Formula binding not yet available")
        # This is an orchestration compatibility contract, never executable data.
        if row["LessonId"] == "Lesson01":
            require(bool(row["CTA_CN"]) == (sid in ACK_STEPS), f"{sid}: CTA must match code-owned acknowledgement")
            require(sid in ACK_STEPS or row["SurfaceType"] == "CompactActionBar", f"{sid}: production actions require CompactActionBar")
    spans = {}
    for row in data["emphasis"]:
        identity = row["LessonId"], row["StepId"]
        require(identity in indexes["steps"], f"Unknown emphasis step: {identity}")
        require(row["Field"] in {"TitleCN", "BodyCN"}, "Only white title/body support emphasis")
        require(row["Style"] == "PerGlyphDots", "Unsupported emphasis Style")
        require(type(row["Occurrence"]) is int and 1 <= row["Occurrence"] <= 20, "Occurrence must be 1..20")
        require(bool(row["MatchText"]), "MatchText is required")
        placeholders(row["MatchText"])
        span = emphasis_range(indexes["steps"][identity][row["Field"]], row["MatchText"], row["Occurrence"])
        key = (*identity, row["Field"])
        require(all(span[1] <= a or span[0] >= b for a, b in spans.get(key, [])), f"Duplicate/overlapping emphasis: {key}")
        spans.setdefault(key, []).append(span)
    for row in data["timings"]:
        value = row["Value"]
        require(type(value) in (int, float) and math.isfinite(value) and 0 <= value <= 60, f"{row['TimingId']}: timing outside 0..60")
        if row["TimingId"] in {"OpponentDeployMove", "ComparisonPace"}:
            require(0.05 <= value <= (2 if row["TimingId"] == "ComparisonPace" else 10), "Movement/pace must be positive and bounded")
    for row in data["labels"]:
        require(bool(row["TextCN"]), f"{row['LabelId']}: text required")
        require(not set(placeholders(row["TextCN"])) & {"CurrentAttackTP", "Formula.AttackBaseValue"}, "Global labels require static bindings")
    require("Lesson01" in lessons and lessons["Lesson01"]["Enabled"], "Enabled Lesson01 is required")
    for group, expected in (("steps", STEPS), ("timings", TIMINGS), ("labels", LABELS)):
        require({key for lid, key in indexes[group] if lid == "Lesson01"} == set(expected), f"Lesson01 {group}: missing/unknown code binding")
    values = {r["TimingId"]: r["Value"] for r in data["timings"] if r["LessonId"] == "Lesson01"}
    require(values["HintFirstDelay"] <= values["HintSecondDelay"], "Hint delays must be ordered")
    return data


def generate(path=SOURCE):
    data = {"schemaVersion": SCHEMA_VERSION, "sourceWorkbook": path.name,
            "sourceWorkbookSha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    for sheet, headers in HEADERS.items():
        rows = read_sheet_rows(path, sheet)
        require(rows and rows[0] == headers, f"{sheet}: exact headers required: {headers}")
        result = []
        for number, cells in enumerate(rows[1:], 2):
            if not any(value is not None for value in cells):
                continue
            require(len(cells) <= len(headers), f"{sheet}:{number}: unexpected column")
            row = dict(zip(headers, cells + [None] * (len(headers) - len(cells))))
            for key in headers:
                if key in {"Enabled", "ShowExit"}:
                    require(row[key] in (0, 1, True, False), f"{sheet}:{number}: {key} must be TRUE/FALSE")
                    row[key] = bool(row[key])
                elif key not in {"SchemaVersion", "Occurrence", "Value"}:
                    require(row[key] is None or isinstance(row[key], str), f"{sheet}:{number}: {key} must be text")
                    row[key] = row[key] or ""
            result.append(row)
        data[sheet.lower()] = result
    # Formula cells are never source content, even if they have a cached value.
    import zipfile
    from xml.etree import ElementTree as ET
    with zipfile.ZipFile(path) as archive:
        for name in archive.namelist():
            if name.startswith("xl/worksheets/") and name.endswith(".xml"):
                require(not ET.fromstring(archive.read(name)).findall(".//{*}f"), "Tutorial source must contain literal values, not Excel formulas")
    validate(data)
    for group, key in (("lessons", "LessonId"), ("steps", "StepId"), ("timings", "TimingId"), ("labels", "LabelId")):
        data[group].sort(key=lambda r: (r["LessonId"], r[key]))
    data["emphasis"].sort(key=lambda r: (r["LessonId"], r["StepId"], r["Field"], r["MatchText"], r["Occurrence"]))
    return data


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=SOURCE)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--check", action="store_true")
    modes.add_argument("--write", action="store_true")
    args = parser.parse_args()
    try:
        data = generate(args.input)
        text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        if args.check:
            require(args.output.exists() and args.output.read_text(encoding="utf-8") == text, "Generated tutorial JSON is stale/missing; run --write")
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n", dir=args.output.parent, delete=False) as f:
                f.write(text)
                temp = Path(f.name)
            temp.replace(args.output)
        print(f"PASS: tutorial schema={SCHEMA_VERSION}, steps={len(data['steps'])}, mode={'check' if args.check else 'write'}")
        return 0
    except (ValidationFailure, OSError, ValueError) as error:
        print(f"FAIL: {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
